### ISSUE TITLE
Convert outside switch into a light-switch

### ISSUE THREAD

**Issue by Per4merKC** [Per4merKC/ha_config#7]
See: https://www.home-assistant.io/components/light.switch/

Sample:
```yaml
light:
  - platform: switch
    name: Christmas Tree Lights
    entity_id: switch.christmas_tree_lights
```
